/*/*/adaptive_clustering:
  ros__parameters:
    cluster_size_max: [1500, 500, 400, 200, 100] # Increase max cluster sizes for farther regions
    cluster_size_min: [80, 45, 30, 20, 15]          # Allow smaller clusters in farther regions
    generate_bounding_boxes: true
    k_merging_threshold: [0.65, 0.75, 0.75, 0.75, 0.75] # Increase merging threshold for farther regions
    leaf: 1
    print_fps: false
    radius_max: 50.0
    radius_min: 0.2
    sensor_model: VLP-16
    z_axis_max: 6.0
    z_axis_min: -1.0
    z_merging_threshold: 0.0
    car_width: 2.0
    car_length: 4.8768
    regions: [10, 10, 10, 10, 10]  # Equal 10m-sized regions for consistent tuning
    region_max: 5
    tolerance: [1.0, 1.2, 1.3, 1.4, 1.5]  # Gradually relaxed clustering tolerance






#/*/*/adaptive_clustering:
#  ros__parameters:
#    cluster_size_max: [750, 500, 250, 150, 100] #750
#    cluster_size_min: [100, 80, 60, 35, 20] #15
#    generate_bounding_boxes: true
#    k_merging_threshold: 0.10000000149011612
#    leaf: 1
#    print_fps: false
#    radius_max: 120.0
#    radius_min:  0.4000000059604645
#    sensor_model: VLP-16
#    z_axis_max: 2.0 
#    z_axis_min: -0.800000011920929
#    z_merging_threshold: 0.0 # not used
#    car_width: 2.0
#    car_length: 4.8768
#    regions: [10, 8, 12, 10, 10]
#    region_max: 5
#    tolerance: 0.5